import {Question} from './question.model'

export const QUESTIONS: Question[]=[
  {
    id:1,
    question_title:"What is democracy?",
    question_desc:"Key aspects and examples of democracy, especially modern democracies",
    category_id:1,
    upvotes:0,
    downvotes:1,
  },
  {
    id:2,
    question_title:"What is dictatorship?",
    question_desc:"Key aspects and examples of dictatorship, especially modern democracies",
    category_id:1,
    upvotes:0,
    downvotes:1,
  },
  {
    id:3,
    question_title:"Is the UN an effective body?",
    question_desc:"Influence of US on UN",
    category_id:1,
    upvotes:0,
    downvotes:1,
  },
  {
    id:4,
    question_title:"What is democracy?",
    question_desc:"Key aspects and examples of democracy, especially modern democracies",
    category_id:1,
    upvotes:0,
    downvotes:1,
  },
  {
    id:5,
    question_title:"What is Laplace equation?",
    question_desc:"Give equation, also how to solve",
    category_id:1,
    upvotes:2,
    downvotes:1,
  },
  {
    id:6,
    question_title:"What is Euclidean geometry?",
    question_desc:"Key aspects and examples of democracy, especially modern democracies",
    category_id:2,
    upvotes:3,
    downvotes:1,
  },
  {
    id:7,
    question_title:"How to prove pythogorus theorem?",
    question_desc:"...",
    category_id:2,
    upvotes:0,
    downvotes:1,
  },
  {
    id:8,
    question_title:"What are black holes?",
    question_desc:"..",
    category_id:3,
    upvotes:0,
    downvotes:1,
  },
  {
    id:9,
    question_title:"What is photoelectric effect?",
    question_desc:"...",
    category_id:3,
    upvotes:0,
    downvotes:1,
  },
  {
    id:10,
    question_title:"What is you opinion about #NotAllMen?",
    question_desc:"...",
    category_id:4,
    upvotes:0,
    downvotes:1,
  },
]
